# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
workspace = "."
paths = [
	"App"
	,"www"
	]
includes = [
	"vendor",
	]
excludes = [
	"files",
	]

[formatter]
preset = "hack"

[linter]
integrations = ["phpunit"]

[linter.rules]
ambiguous-function-call = { enabled = true }
use-dedicated-expectation = { enabled = true }
use-simpler-expectation = { enabled = true }
use-specific-expectations = { enabled = true }
assert-description = { enabled = true }
assertion-style = { enabled = true }
block-statement = { enabled = true }
braced-string-interpolation = { enabled = true }
class-name = { enabled = false }
combine-consecutive-issets = { enabled = true }
constant-name = { enabled = true }
cyclomatic-complexity = { enabled = false }
disallowed-functions = { enabled = true }
enum-name = { enabled = true }
excessive-nesting = { enabled = false }
excessive-parameter-list = { enabled = false }
final-controller = { enabled = true }
halstead = { enabled = false }
kan-defect = { enabled = false }
literal-named-argument = { enabled = false }
loop-does-not-iterate = { enabled = true }
lowercase-keyword = { enabled = true }
no-debug-symbols = { enabled = true }
no-request-variable = { enabled = true }
no-shell-execute-string = { enabled = true }
no-short-opening-tag = { enabled = true }
no-shorthand-ternary = { enabled = false }
no-sprintf-concat = { enabled = true }
optional-param-order = { enabled = true }
prefer-anonymous-migration = { enabled = true }
prefer-first-class-callable = { enabled = true }
no-void-reference-return = { enabled = true }
no-underscore-class = { enabled = true }
no-trailing-space = { enabled = true }
no-redundant-write-visibility = { enabled = true }
no-redundant-string-concat = { enabled = true }
no-redundant-parentheses = { enabled = true }
no-redundant-method-override = { enabled = true }
no-redundant-nullsafe = { enabled = true }
no-redundant-math = { enabled = true }
no-redundant-label = { enabled = true }
no-redundant-literal-return = { enabled = true }
no-redundant-final = { enabled = true }
no-redundant-readonly = { enabled = true }
no-redundant-file = { enabled = false }
no-redundant-continue = { enabled = true }
no-redundant-block = { enabled = true }
no-redundant-use = { enabled = true }
no-redundant-yield-from = { enabled = true }
no-self-assignment = { enabled = true }
no-protected-in-final = { enabled = true }
no-php-tag-terminator = { enabled = true }
no-noop = { enabled = true }
no-only = { enabled = true }
no-multi-assignments = { enabled = false }
no-nested-ternary = { enabled = true }
no-hash-emoji = { enabled = true }
no-hash-comment = { enabled = true }
no-variable-variable = { enabled = true }
no-goto = { enabled = true }
no-global = { enabled = true }
no-ffi = { enabled = true }
no-eval = { enabled = true }
no-error-control-operator = { enabled = false }
no-empty = { enabled = false }
no-empty-loop = { enabled = true }
no-empty-comment = { enabled = true }
no-empty-catch-clause = { enabled = true }
no-else-clause = { enabled = false }
no-closing-tag = { enabled = true }
no-boolean-flag-parameter = { enabled = false }
no-assign-in-argument = { enabled = false }
no-assign-in-condition = { enabled = false }
no-alias-function = { enabled = true }
lowercase-type-hint = { enabled = true }
identity-comparison = { enabled = false }
ineffective-format-ignore-next = { enabled = true }
ineffective-format-ignore-region = { enabled = true }
inline-variable-return = { enabled = true }
instanceof-stringable = { enabled = true }
interface-name = { enabled = true }
invalid-open-tag = { enabled = true }
function-name = { enabled = true }
explicit-nullable-param = { enabled = true }
explicit-octal = { enabled = true }
prefer-arrow-function = { enabled = true }
prefer-early-continue = { enabled = false }
prefer-interface = { enabled = true }
prefer-static-closure = { enabled = true }
prefer-view-array = { enabled = true }
prefer-while-loop = { enabled = true }
psl-array-functions = { enabled = true }
psl-data-structures = { enabled = true }
psl-datetime = { enabled = true }
psl-math-functions = { enabled = true }
psl-output = { enabled = true }
psl-randomness-functions = { enabled = true }
psl-regex-functions = { enabled = true }
psl-sleep-functions = { enabled = true }
psl-string-functions = { enabled = true }
str-contains = { enabled = true }
str-starts-with = { enabled = true }
strict-behavior = { enabled = false }
strict-types = { enabled = false }
tagged-fixme = { enabled = true }
tagged-todo = { enabled = true }
too-many-enum-cases = { enabled = true }
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }
trait-name = { enabled = true }
valid-docblock = { enabled = true }
variable-name = { enabled = false }
constant-condition = { enabled = true }
no-ini-set = { enabled = false }
no-insecure-comparison = { enabled = true }
no-literal-password = { enabled = false }
no-isset = { enabled = false }
tainted-data-to-sink = { enabled = true }
sensitive-parameter = { enabled = false }
property-name = { enabled = false }
no-unsafe-finally = { enabled = true }
strict-assertions = { enabled = true }
use-specific-assertions = { enabled = true }
no-request-all = { enabled = true }
middleware-in-routes = { enabled = true }
use-compound-assignment = { enabled = false }
require-preg-quote-delimiter = { enabled = true }
require-namespace = { enabled = true }
readable-literal = { enabled = false }
yoda-conditions = { enabled = true }
use-wp-functions = { enabled = true }
no-direct-db-query = { enabled = true }
no-db-schema-change = { enabled = true }
no-unescaped-output = { enabled = true }
no-roles-as-capabilities = { enabled = true }

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
#`excludes`, `ignore`, `baseline`, `baseline-variant`, `disable-default-plugins`, `plugins`, `find-unused-expressions`, `find-unused-definitions`, `analyze-dead-code`, `memoize-properties`, `allow-possibly-undefined-array-keys`, `check-throws`, `unchecked-exceptions`, `unchecked-exception-classes`, `strict-list-index-checks`, `no-boolean-literal-comparison`, `check-missing-type-hints`, `check-closure-missing-type-hints`, `check-arrow-function-missing-type-hints`, `register-super-globals`, `check-missing-override`, `find-unused-parameters`, `trust-existence-checks`, `class-initializers`, `check-property-initialization`, `check-use-statements`, `perform-heuristic-checks`, `performance` for key `analyzer`
